### PR TITLE
Update build scripts to update deps

### PR DESCRIPTION
**Pull request by mgattozzi**
Cargo.lock is part of the build which is fine for reproducible builds.
However, with the use of nightly and unstable features in things like
rls-analysis it means things can break and already have quite a bit.
This commit relaxes the constraints on rls-analysis to use the newest
version (which is good so we can identify problems later) and adds
a `cargo update` to the CI builds to avoid problems with using older
cached versions of rls-analysis.

cc/ @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
@nrc what do you think of this change? I am of two minds.

**Comment by mgattozzi** [comment]
I'd also be fine with making the update to the dep version just so we can fix the build. Either works.

**Comment by nrc** [comment]
I feel like I'm missing something. Won't this make you break more often? Because you'll randomly pull in every upstream change, some of which might be breaking? You still get breakage due to nightly changes until that is fixed upstream, so it seems the only advantage is that once something is fixed upstream, you get the fix quicker?

**Comment by mgattozzi** [comment]
Yeah my wording was incorrect I think. It's mostly we get upstream fixes quicker. We could just update the dep and have Travis run a nightly Cron job that will ping at least @steveklabnik if there's a breaking change instead.

**Comment by steveklabnik** [comment]
That is https://github.com/steveklabnik/rustdoc/issues/158, which I thought I fixed, but did not.

@mgattozzi yeah, let's go with that. Let's change up this PR to only update the dep, and I will bump #158 up in priority for me 😄

**Comment by mgattozzi** [comment]
@steveklabnik I've updated the PR and changed the commit to better reflect the change.

**Comment by steveklabnik** [comment]
Thanks!

**Pull request merged**
